name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore: 
      - .github/workflows/*

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'QuickUninstaller/plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}} 
      - name: Build
        run: |
          dotnet publish 'QuickUninstaller/Wox.Plugin.QuickUninstaller.csproj' -r win-x64  -c Release -o "QuickUninstaller-${{steps.version.outputs.prop}}"
          7z a -tzip "QuickUninstaller.zip" "./QuickUninstaller-${{steps.version.outputs.prop}}/*"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "QuickUninstaller*"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
